## Put comments here that give an overall description of what your
## functions do

## R Programming - Week 3 programming assignment

## "makeCacheMatrix" generates a list of 4 functions that allow the
## user to set or get the value of a matrix, and to set or get the
## inverse of that matrix
##
## Example:
## > mymatrix<-matrix(c(1,3,4,3,4,2,7,5,4),3,3)
## > k <- makeCacheMatrix()
## > k$set(mymatrix)
## > k$get()
## [,1] [,2] [,3]
## [1,]    1    3    7
## [2,]    3    4    5
## [3,]    4    2    4
##

makeCacheMatrix <- function(x = matrix()) {

		m<-NULL
		set<-function(y) {
		     x<<- y
		     m<<-NULL
		}

		get <- function() x
		
		setinvmatrix <- function(invmatrix) m <<- invmatrix
		
		getinvmatrix <- function() m
		
		list(set = set, get = get, setinvmatrix = setinvmatrix, 
		     getinvmatrix = getinvmatrix)
}


## "cacheSolve" returns the inverse of a matrix that is generated by
## "makeCacheMatrix". If the inverse has already been computed, it is taken
## from the cache, otherwise the program performs the matrix inversion.
##
## Example (to be run after executing previous example):
## > l <- cacheSolve(k)
## > l
## [,1]  [,2]   [,3]
## [1,] -0.15 -0.05  0.325
## [2,] -0.20  0.60 -0.400
## [3,]  0.25 -0.25  0.125

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    
    m <- x$getinvmatrix()
    
    if(!is.null(m)) {
            message("getting the cached inverted matrix")
            return(m)
    }
    
    data <- x$get()
     
    invmatrix <- solve(data, ...)
    
    x$setinvmatrix(invmatrix)
    
    invmatrix
    
}

